name: Python ECAT Test
on:
  push:
  pull_request:
    branches:
      - main
  
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Get Working Dir
        run: pwd

      - name: List Working Dir Contents
        run: ls -l

      - name: Install Python Requirements
        run: pip3 install -r python/requirements.txt

      - name: Test CLI --help
        run: python3 python/main.py --help
