name: Python ECAT Test
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Collect-Data-and-Test:

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Get Working Dir
        run: pwd

      - name: List Working Dir Contents
        run: ls -l
